# Generated by Django 4.0.4 on 2022-06-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='img',
            new_name='image',
        ),
    ]
